services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WernerDweight\DoctrineCrudApiBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Exception}'

    WernerDweight\DoctrineCrudApiBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    WernerDweight\DoctrineCrudApiBundle\Service\Data\ServiceEntityRepositoryFactory:
        arguments:
            $repositories: !tagged doctrine.repository_service
