services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WernerDweight\DoctrineCrudApiBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Exception}'

    WernerDweight\DoctrineCrudApiBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    WernerDweight\DoctrineCrudApiBundle\Service\Data\ServiceEntityRepositoryFactory:
        arguments:
            $repositories: !tagged doctrine.repository_service

    WernerDweight\DoctrineCrudApiBundle\Mapping\DoctrineCrudApiEventSubscriber:
        tags: ['doctrine.event_subscriber']

    WernerDweight\DoctrineCrudApiBundle\Mapping\Driver\:
        resource: '../../Mapping/Driver/*'
        exclude: '../../Mapping/Driver/Abstract*'
        tags:
            - { name: 'crud_api.driver' }

    WernerDweight\DoctrineCrudApiBundle\Mapping\DoctrineCrudApiDriverFactory:
        arguments:
            $drivers: !tagged crud_api.driver
